 Region.create(abbreviation: 'AL', name: 'Alabama')
 Region.create(abbreviation: 'AK', name: 'Alaska')
 Region.create(abbreviation: 'AZ', name: 'Arizona')
 Region.create(abbreviation: 'AR', name: 'Arkansas')
 Region.create(abbreviation: 'CA', name: 'California')
 Region.create(abbreviation: 'CO', name: 'Colorado')
 Region.create(abbreviation: 'CT', name: 'Connecticut')
 Region.create(abbreviation: 'DE', name: 'Delaware')
 Region.create(abbreviation: 'DC', name: 'District of Columbia')
 Region.create(abbreviation: 'FL', name: 'Florida')
 Region.create(abbreviation: 'GA', name: 'Georgia')
 Region.create(abbreviation: 'HI', name: 'Hawaii')
 Region.create(abbreviation: 'ID', name: 'Idaho')
 Region.create(abbreviation: 'IL', name: 'Illinois')
 Region.create(abbreviation: 'IN', name: 'Indiana')
 Region.create(abbreviation: 'IA', name: 'Iowa')
 Region.create(abbreviation: 'KS', name: 'Kansas')
 Region.create(abbreviation: 'KY', name: 'Kentucky')
 Region.create(abbreviation: 'LA', name: 'Louisiana')
 Region.create(abbreviation: 'ME', name: 'Maine')
 Region.create(abbreviation: 'MD', name: 'Maryland')
 Region.create(abbreviation: 'MA', name: 'Massachusetts')
 Region.create(abbreviation: 'MI', name: 'Michigan')
 Region.create(abbreviation: 'MN', name: 'Minnesota')
 Region.create(abbreviation: 'MS', name: 'Mississippi')
 Region.create(abbreviation: 'MO', name: 'Missouri')
 Region.create(abbreviation: 'MT', name: 'Montana')
 Region.create(abbreviation: 'NE', name: 'Nebraska')
 Region.create(abbreviation: 'NV', name: 'Nevada')
 Region.create(abbreviation: 'NH', name: 'New Hampshire')
 Region.create(abbreviation: 'NJ', name: 'New Jersey')
 Region.create(abbreviation: 'NM', name: 'New Mexico')
 Region.create(abbreviation: 'NY', name: 'New York')
 Region.create(abbreviation: 'NC', name: 'North Carolina')
 Region.create(abbreviation: 'ND', name: 'North Dakota')
 Region.create(abbreviation: 'OH', name: 'Ohio')
 Region.create(abbreviation: 'OK', name: 'Oklahoma')
 Region.create(abbreviation: 'OR', name: 'Oregon')
 Region.create(abbreviation: 'PA', name: 'Pennsylvania')
 Region.create(abbreviation: 'RI', name: 'Rhode Island')
 Region.create(abbreviation: 'SC', name: 'South Carolina')
 Region.create(abbreviation: 'SD', name: 'South Dakota')
 Region.create(abbreviation: 'TN', name: 'Tennessee')
 Region.create(abbreviation: 'TX', name: 'Texas')
 Region.create(abbreviation: 'UT', name: 'Utah')
 Region.create(abbreviation: 'VT', name: 'Vermont')
 Region.create(abbreviation: 'VA', name: 'Virginia')
 Region.create(abbreviation: 'WA', name: 'Washington')
 Region.create(abbreviation: 'WV', name: 'West Virginia')
 Region.create(abbreviation: 'WI', name: 'Wisconsin')
 Region.create(abbreviation: 'WY', name: 'Wyoming')
 Region.create(abbreviation: 'PR', name: 'Puerto Rico')
 
 Category.create(name: 'Community')
 Category.create(name: 'Housing')
 Category.create(name: 'For Sale')
 Category.create(name: 'Services')
 Category.create(name: 'Jobs')

puts 'SETTING UP DEFAULT USER LOGIN'
user = User.create! :name => 'First User', :email => 'user@example.com', :password => 'please', :password_confirmation => 'please'
puts 'New user created: ' << user.name
user2 = User.create! :name => 'Second User', :email => 'user2@example.com', :password => 'please', :password_confirmation => 'please'
puts 'New user created: ' << user2.name
user.add_role :admin